const fs = require('fs');

let code = fs.readFileSync('src/App.tsx', 'utf-8');

const TRANSLATIONS_REGEX = /const TRANSLATIONS = \{[\s\S]*?\}\n\};\n\n/m;

const NEW_TRANSLATIONS = `const TRANSLATIONS = {
  zh: {
    ticker: "✨ Mona 首张专辑 'No.1' POPUP STORE 举办中！周边贩售及握手会详情请点击查看 · 🎀 全新单曲 MV 视听解禁！ · ✨ Mona 首张专辑 'No.1' POPUP STORE 举办中！",
    fanSite: "mona粉丝站",
    recommended: "推荐单曲",
    producer: "致：制作人",
    profile: "人物介绍",
    personality: "性格特点",
    background: "背景故事",
    relMap: "人物关系图",
    sister: "成海圣奈 (姐姐)",
    fans: "粉丝们",
    mostImportant: "最重要的人",
    reasons: "被吸引的理由",
    fansVoice: "粉丝心声",
    discography: "作品集",
    latest: "单曲试听",
    mvPreview: "MV赏析",
    playing: "播放中",
    boardTitle: "粉丝留言板",
    boardSubtitle: "支持与热爱，送给最闪耀的偶像！",
    post: "发布留言",
    placeholder: "写下你对 Mona 酱的热爱吧！✨",
    thanks: "来自 Mona 的谢意",
    loveYou: "最喜欢你了！",
    monaBio: "性格元气努力、不服输、要强又可爱。怀揣着“我也要在属于我的舞台上闪耀”的决心，Mona 踏上了残酷又绚丽的偶像之路。为了梦想，她目前全心投入事业，暂时没有恋爱计划。",
    monaStory: "2018年3月以《我的偶像宣言》正式出道。拒绝靠着姐姐成海圣奈的名气，坚持凭自己的努力在寺门艺能事务所作为新人偶像奋斗。2021年发行首张个人专辑，如今已是一线新人偶像。",
    details: { birthday: "4月24日", age: "16岁（高一）", height: "160cm", blood: "AB型", cv: "夏川椎菜", identity: "寺门艺能所属偶像" },
    relSena: "成海圣奈", relSenaDesc: "最强后盾 / 竞争对手", relLIP: "LIP×LIP", relLIPDesc: "同事 / 目标", relMinami: "南 (Minami)", relMinamiDesc: "好友 / YouTuber",
    historyTitle: "星光历程",
    historyItems: ["2018.03 以《我的偶像宣言》正式出道", "拒绝靠姐姐名气，坚持凭自己努力在寺门艺能奋斗", "2021.02 发布首张个人专辑《#No.1》", "举办多场个人演唱会，与粉丝建立了最深厚的羁绊"],
    role: "超级偶像", name: "成海 萌奈", love: "爱心！", shaping: "塑造成长中", clickOpen: "点击开始了解",
    producerLabel: "致：制作人", loveText: "ラブ！", relSister: "姐姐", relSisterStatus: "憧憬/自卑", relFans: "双向奔赴", relFansStatus: "最重要的人",
    quotes: [
      { text: "「总是全力以赴，把粉丝放在第一位的样子最喜欢了！」", Author: "来自后援会的A君" },
      { text: "「虽然偶尔有些小迷糊，但在舞台上比谁都要闪耀✨」", Author: "永远单推的B酱" },
      { text: "「每一次的饭撒都精准击中我的心！绝对会一直支持你！」", Author: "被饭撒拯救的C酱" },
      { text: "「看着Mona一步步走向顶点，真的很感动，这就是养成系偶像的魅力吧！」", Author: "某位老粉留" },
    ],
    songs: [
      { title: '私、アイドル宣言', desc: '最初的偶像宣言！一起享受舞台吧。', tag: '经典·出道' },
      { title: 'ファンサ', desc: '用实力获胜！最棒的饭撒送给你。', tag: '百万热门' },
      { title: 'No.1', desc: '向着梦想闪耀的轨迹。', tag: '专辑主打' },
      { title: '誇り高きアイドル', desc: '骄傲的偶像，挥洒汗水与泪水的舞台。', tag: 'Live人气曲' },
      { title: '人生は最高の暇つぶし', desc: '坚持做自己，保持自信。', tag: '病毒式走红' },
    ]
  },
  ja: {
    ticker: "✨ Mona 1st Album 'No.1' POPUP STORE 開催中！グッズ販売や握手会の詳細をチェック · 🎀 新曲MV先行公開中！ · ✨ Mona 1st Album 'No.1' POPUP STORE 開催中！",
    fanSite: "monaファンサイト",
    recommended: "おすすめ曲",
    producer: "To: プロデューサーへ",
    profile: "プロフィール",
    personality: "性格",
    background: "経歴",
    relMap: "相関図",
    sister: "成海聖奈 (お姉ちゃん)",
    fans: "ファンの皆さん",
    mostImportant: "大事な人",
    reasons: "私たちが惹かれる理由",
    fansVoice: "ファンの声",
    discography: "ディスコグラフィ",
    latest: "シングル試聴",
    mvPreview: "MV鑑賞",
    playing: "再生中",
    boardTitle: "ファン掲示板",
    boardSubtitle: "輝くアイドルへ、愛と応援を届けよう！",
    post: "投稿する",
    placeholder: "Monaちゃんへの愛を叫ぼう！✨",
    thanks: "Monaからのメッセージ",
    loveYou: "大好きだよ！",
    monaBio: "負けず嫌いで、情熱と活力に満ちた努力家！時折不器用な面も見せますが、ファンの前では常に120%の完璧な笑顔を絶やしません。夢のために、現在は恋愛禁止で活動中。",
    monaStory: "2018年3月『私、アイドル宣言』でデビュー。姉・成海聖奈に頼らず、自らの力で輝くことを決意。寺門芸能所属の新人アイドルとして奮闘し、2021年には1stアルバムをリリースしました。",
    details: { birthday: "4月24日", age: "16歳（高一）", height: "160cm", blood: "AB型", cv: "夏川椎菜", identity: "寺門芸能所属アイドル" },
    relSena: "成海聖奈", relSenaDesc: "最強の味方 / ライバル", relLIP: "LIP×LIP", relLIPDesc: "同僚 / 目標", relMinami: "南 (Minami)", relMinamiDesc: "親友 / YouTuber",
    historyTitle: "活動ヒストリー",
    historyItems: ["2018.03 『私、アイドル宣言』で本格デビュー", "姉・聖奈の力に頼らず、寺門芸能にて自らの力で活動", "2021.02 1stアルバム『#No.1』をリリース", "ワンマンライブ開催など、ファンと共に歩み続けています"],
    role: "#No.1 アイドル", name: "成海 萌奈", love: "大好き！", shaping: "成長中", clickOpen: "アーカイブを開く",
    producerLabel: "To: プロデューサー", loveText: "ラブ！", relSister: "姉", relSisterStatus: "憧れ/劣等感", relFans: "相愛", relFansStatus: "大事な人",
    quotes: [
      { text: "「常に全力投球で、ファンを第一に考える姿が大好きです！」", Author: "後援会のA君より" },
      { text: "「時々ドジなところもあるけど、ステージでは誰よりも輝いてる✨」", Author: "永遠の単推しBちゃん" },
      { text: "「ファンサのたびにハートを射抜かれます！ずっと応援するよ！」", Author: "ファンサに救われたCちゃん" },
      { text: "「Monaが頂点へ向かう姿に感動しています。これがアイドルの魅力！」", Author: "とある古参ファンより" },
    ],
    songs: [
      { title: '私、アイドル宣言', desc: '最強アイドルの甘えん坊宣言！ハートを感じて。', tag: 'デビュー曲' },
      { title: 'ファンサ', desc: '実力で心をつかむ！最高のファンサをあなたに。', tag: 'ミリオンヒット' },
      { title: 'No.1', desc: '夢に向かって輝く軌跡。', tag: 'アルバムタイトル' },
      { title: '誇り高きアイドル', desc: '誇り高きアイドル、汗と涙のステージ。', tag: 'ライブ人気' },
      { title: '人生は最高の暇つぶし', desc: '自分らしく、絶対自信のスイートアタック。', tag: 'バイラルヒット' },
    ]
  },
  en: {
    ticker: "✨ Mona 1st Album 'No.1' POPUP STORE Now Open! Check out merch & handshake events · 🎀 New MV released! · ✨ Mona 1st Album 'No.1' POPUP STORE Now Open!",
    fanSite: "Mona Fansite",
    recommended: "Recommended",
    producer: "To: Producer",
    profile: "Profile",
    personality: "Personality",
    background: "Background",
    relMap: "Relationships",
    sister: "Sena Narumi (Sister)",
    fans: "Fans",
    mostImportant: "Most Important",
    reasons: "Why We Love Her",
    fansVoice: "Fan Voices",
    discography: "Discography",
    latest: "Single Previews",
    mvPreview: "MV Previews",
    playing: "Now Playing",
    boardTitle: "Fan Board",
    boardSubtitle: "Send love & support to our shining idol!",
    post: "Post",
    placeholder: "Express your love for Mona! ✨",
    thanks: "Message from Mona",
    loveYou: "I love you all!",
    monaBio: "Energetic, competitive, and full of vitality! Though sometimes clumsy, she never fails to show a 120% perfect smile to her fans. Currently putting romance on pause to focus entirely on her dream.",
    monaStory: "Debuted in March 2018 with 'Watashi, Idol Sengen'. Determined to shine on her own merits without relying on her sister's fame. Released her 1st album in 2021 as a rising top idol.",
    details: { birthday: "April 24", age: "16 (1st Year HS)", height: "160cm", blood: "AB", cv: "Shiina Natsukawa", identity: "Idol at Terakado Ent." },
    relSena: "Sena Narumi", relSenaDesc: "Biggest Supporter / Rival", relLIP: "LIP×LIP", relLIPDesc: "Colleagues / Goal", relMinami: "Minami", relMinamiDesc: "Best Friend / YouTuber",
    historyTitle: "Idol Journey",
    historyItems: ["Mar 2018: Debuted with 'Watashi, Idol Sengen'", "Forged her own path at Terakado Entertainment", "Feb 2021: Released 1st Album '#No.1'", "Held solo concerts, building strong bonds with fans"],
    role: "Super Idol", name: "Mona Narumi", love: "Love!", shaping: "Growing", clickOpen: "Click to Open",
    producerLabel: "To: Producer", loveText: "Love!", relSister: "Sister", relSisterStatus: "Admiration", relFans: "Mutual Love", relFansStatus: "Most Important",
    quotes: [
      { text: "I love how she always goes all out and puts fans first!", Author: "Fan Club Member A" },
      { text: "She might be a bit clumsy sometimes, but on stage she shines brighter than anyone ✨", Author: "Forever Fan B" },
      { text: "Her fan service hits me right in the heart every time!", Author: "Saved by Fan Service C" },
      { text: "Watching Mona reach the top is incredibly moving. That's the charm of an idol!", Author: "Veteran Fan" },
    ],
    songs: [
      { title: 'Watashi, Idol Sengen', desc: 'The first idol declaration! Enjoy the stage.', tag: 'Debut' },
      { title: 'Fansa', desc: 'Winning hearts with skill! The best fanservice.', tag: 'Million Hit' },
      { title: 'No.1', desc: 'The shining path towards dreams.', tag: 'Album Lead' },
      { title: 'Hokori Takaki Idol', desc: 'A proud idol, a stage of sweat and tears.', tag: 'Live Favorite' },
      { title: 'Jinsei wa Saikou no Himatsubushi', desc: 'Stay true to yourself with absolute confidence.', tag: 'Viral Hit' },
    ]
  },
  ko: {
    ticker: "✨ Mona 첫 정규 앨범 'No.1' 팝업 스토어 진행 중! 굿즈 및 악수회 정보 확인 · 🎀 신곡 MV 선행 공개! · ✨ Mona 첫 정규 앨범 'No.1' 팝업 스토어 진행 중!",
    fanSite: "모나 팬사이트",
    recommended: "추천곡",
    producer: "To: 프로듀서",
    profile: "프로필",
    personality: "성격",
    background: "배경 이야기",
    relMap: "인물 관계도",
    sister: "나루미 세나 (언니)",
    fans: "팬 여러분",
    mostImportant: "가장 소중한 사람",
    reasons: "매력 포인트",
    fansVoice: "팬들의 목소리",
    discography: "디스코그래피",
    latest: "싱글 미리듣기",
    mvPreview: "MV 미리보기",
    playing: "재생 중",
    boardTitle: "팬 게시판",
    boardSubtitle: "가장 빛나는 아이돌에게 사랑과 응원을!",
    post: "작성",
    placeholder: "모나를 향한 사랑을 적어주세요! ✨",
    thanks: "모나의 메시지",
    loveYou: "정말 사랑해요!",
    monaBio: "지기 싫어하고 활기찬 노력가! 가끔 서투른 모습도 보이지만 팬들 앞에서는 항상 120%의 완벽한 미소를 보여줍니다. 꿈을 위해 현재는 연애금지!",
    monaStory: "2018년 3월 '나, 아이돌 선언'으로 데뷔. 언니 세나의 후광 없이 자신의 힘으로 빛나기로 결심하고 테라카도 예능에서 고군분투 중. 2021년 1st 앨범 발매.",
    details: { birthday: "4월 24일", age: "16세 (고1)", height: "160cm", blood: "AB형", cv: "나츠카와 시이나", identity: "테라카도 소속 아이돌" },
    relSena: "나루미 세나", relSenaDesc: "최고의 아군 / 라이벌", relLIP: "LIP×LIP", relLIPDesc: "동료 / 목표", relMinami: "미나미 (Minami)", relMinamiDesc: "절친 / 유튜버",
    historyTitle: "활동 히스토리",
    historyItems: ["2018.03 '나, 아이돌 선언'으로 본격 데뷔", "언니의 이름에 기대지 않고 자신의 힘으로 활동", "2021.02 1st 앨범 '#No.1' 발매", "단독 라이브 개최 등 팬들과 계속해서 걸어가는 중"],
    role: "최고의 아이돌", name: "나루미 모나", love: "사랑해!", shaping: "성장 중", clickOpen: "클릭하여 열기",
    producerLabel: "To: 프로듀서", loveText: "러브!", relSister: "언니", relSisterStatus: "동경/열등감", relFans: "서로 사랑함", relFansStatus: "가장 소중한 존재",
    quotes: [
      { text: "항상 전력을 다하고 팬을 최우선으로 생각하는 모습이 너무 좋아요!", Author: "팬클럽 A군" },
      { text: "가끔 덜렁대지만 무대 위에서는 누구보다 빛나요✨", Author: "영원한 단오시 B양" },
      { text: "매번 팬서비스에 심장이 멎는 것 같아요! 계속 응원할게요!", Author: "팬서비스에 구원받은 C양" },
      { text: "모나가 정점을 향해 가는 모습을 보면 정말 감동적이에요. 이것이 아이돌의 매력!", Author: "어느 고인물 팬" },
    ],
    songs: [
      { title: '나, 아이돌 선언', desc: '최강 아이돌의 첫 선언! 하트를 느껴봐.', tag: '데뷔곡' },
      { title: '팬서비스', desc: '실력으로 쟁취한다! 최고의 팬서비스를 당신에게.', tag: '밀리언 히트' },
      { title: 'No.1', desc: '꿈을 향해 빛나는 궤적.', tag: '앨범 타이틀' },
      { title: '긍지 높은 아이돌', desc: '긍지 높은 아이돌, 땀과 눈물의 무대.', tag: '라이브 인기곡' },
      { title: '인생은 최고의 시간 낭비', desc: '나답게, 절대적인 자신감의 스위트 어택.', tag: '바이럴 히트' },
    ]
  }
};

`;

const startIdx = code.indexOf('const TRANSLATIONS = {');
const endIdx = code.indexOf('const SONGS = [');

if (startIdx !== -1 && endIdx !== -1) {
  code = code.substring(0, startIdx) + NEW_TRANSLATIONS + code.substring(endIdx);
  fs.writeFileSync('src/App.tsx', code);
}
